#!/usr/bin/env python3
"""Extract the app's SNOWPACK tile engine (vaHiEngine) as an ES module.

The engine is written once, inside pipeline/interactive_export.py, and runs
in the browser's Web Worker. The tile server (tiles/worker) runs the SAME
function server-side, so it is cut out of the built app.js rather than kept
as a second copy that could drift:

    python tools/make_va_engine.py dist/app.js tiles/worker/src/va_engine.js
"""
import sys
from pathlib import Path


def extract(src: str, name: str = "vaHiEngine") -> str:
    i = src.index(f"function {name}(")
    depth = 0
    for k in range(src.index("{", i), len(src)):
        c = src[k]
        if c == "{":
            depth += 1
        elif c == "}":
            depth -= 1
            if depth == 0:
                return src[i:k + 1]
    raise ValueError(f"{name}: unbalanced braces")


def main():
    app, out = Path(sys.argv[1]), Path(sys.argv[2])
    body = extract(app.read_text(encoding="utf-8"))
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text("// GENERATED by tools/make_va_engine.py from the app build -- do not edit.\n"
                   "export " + body + "\n", encoding="utf-8")
    print(f"{out}: {len(body)} chars")


if __name__ == "__main__":
    main()
